name: Test .NET Framework project

inputs:
  target-framework:
    description: 'Target .NET framework'
    required: true
  solution:
    description: 'Solution/project path'
    required: true
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  gist_token:
    description: 'GIST_TOKEN'
    required: true

outputs:
  test-status:
    description: 'Test status'
    value: ${{ steps.test-run.outputs.test-status }}

description: Action for test-core
    
runs:
  using: "composite"
  steps:
    - name: Set the required terget .NET Framework version
      run: |
        if [[ "${{ inputs.target-framework }}" == "net462" ]]; then
          echo "msbuild-version=14" >> $GITHUB_ENV
        elif [[ "${{ inputs.target-framework }}" == "net472" ]]; then
          echo "msbuild-version=15" >> $GITHUB_ENV
        elif [[ "${{ inputs.target-framework }}" == "net48" ]]; then
          echo "msbuild-version=16" >> $GITHUB_ENV
        else
          echo "msbuild-version=16" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Setup MSBuild ${{ env.msbuild-version }}
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        vs-version: '${{ env.msbuild-version }}'
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts-${{ inputs.target-framework }}
    - name: Extract build artifacts
      run: tar -xvzf build-artifacts-${{ inputs.target-framework }}.tar.gz
      shell: bash
    - name: Test with ${{ inputs.target-framework }}
      id: test-run
      run: (dotnet test ${{ inputs.solution }} --logger trx --results-directory ./TestResults --framework ${{ inputs.target-framework }} --no-build --verbosity normal --configuration Release && echo "::set-output name=test-status::0") || echo "::set-output name=test-status::1"
      shell: bash
    - name: Check on failures
      if: steps.test-run.outputs.test-status == 1
      run: exit 1
      shell: bash