name: 'Notification: Issue'

on:
  workflow_dispatch:
  issues:
    types: [ opened, edited, milestoned ]

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on pr events
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RECIPIENT }}
          token: ${{ secrets.TELEGRAM_BOT_API }}
          message: The '${{ github.actor }}' changed issue № ${{ github.event.number}} (${{ github.server_url }}/${{ github.repository }}/issues/${{ github.event.number}})
