name: 'Notification: Check'

on:
  workflow_dispatch:
  issues:

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on issue events
        run: echo "$GITHUB_CONTEXT"
        #uses: appleboy/telegram-action@master
        #with:
        #  to: ${{ secrets.TELEGRAM_RECIPIENT }}
        #  token: ${{ secrets.TELEGRAM_BOT_API }}
        #  message: The '${{ github.actor }}' changed issue № ${{ github.issue.number }} (${{ github.server_url }}/${{ github.repository }}/issues/${{ github.issue.number }})
