name: 'Notification: PR'

on:
  workflow_dispatch:
  pull_request:

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on pr events
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RECIPIENT }}
          token: ${{ secrets.TELEGRAM_BOT_API }}
          message: The '${{ github.actor }}' changed PR ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}
