name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - alpha-release
      - beta-release
      - rc-release
      - release

jobs:
  build:
    env:
      VersionPrefix: 0.0.2
      VersionSuffix: alpha

    runs-on: ubuntu-latest

    steps:
    - name: Set env variables
      run: |
       if [[ ${{ github.ref }} == refs/heads/alpha-release ]] 
       then
         echo "alpha" >> $VersionSuffix
       elif [[ ${{ github.ref }} == refs/heads/beta-release ]]
       then
         echo "beta" >> $VersionSuffix
       elif [[ ${{ github.ref }} == refs/heads/rc-release ]]
       then
         echo "rc" >> $VersionSuffix
       elif [[ ${{ github.ref }} == refs/heads/release ]]
       then
         echo "" >> $VersionSuffix
       fi
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release 
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack ./Packable.slnf --no-build --output ./nupkgs --configuration Release 
    - name: Publish
      run: dotnet nuget push ./nupkgs/ --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
