name: Release

on:
  workflow_dispatch:
    inputs:
      version-prefix:
        description: 'Version'
        required: true
      version-patch:
        description: 'Patch number'     
        required: true
  push:
    branches: [ alpha-release, beta-release, release ]

env:
  version-prefix: 0.10.0
  version-patch: 4
  nuget-source: https://api.nuget.org/v3/index.json
  github-pkgs-source: https://nuget.pkg.github.com/nclient/index.json
      
jobs:
  
  release-dev:
    if: ${{ github.event.inputs.version-prefix }} != '' && ${{ github.event.inputs.version-patch }} != ''
    environment: release-dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Push packaget to NuGet
      uses: ./actions/push
      with:
        version-prefix: ${{ github.event.inputs.version-prefix }}
        version-suffix: dev.${{ github.event.inputs.version-patch }}
        source: ${{ env.github-pkgs-source }}
        source-api-key: ${{ secrets.GITHUB_TOKEN }}
      
  release-dev-validation:
    needs: release-dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Test release
      uses: ./actions/test-release
      with:
        version-prefix: ${{ github.event.inputs.version-prefix }}
        version-suffix: dev.${{ github.event.inputs.version-patch }}
        delay: 30s
        custom-source: ${{ env.github-pkgs-source }}
        custom-source-user: nclient
        custom-source-password: ${{ secrets.GITHUB_TOKEN }}
  
  release-alpha:
    if: github.ref == 'refs/heads/alpha-release'
    environment: release-alpha
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Push packaget to NuGet
      uses: ./actions/push
      with:
        version-prefix: ${{ env.version-prefix }}
        version-suffix: alpha.${{ env.version-patch }}
        source: ${{ env.nuget-source }}
        source-api-key: ${{ secrets.NUGET_API_KEY }}
      
  release-alpha-validation:
    needs: release-alpha
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Test release
      uses: ./actions/test-release
      with:
        version-prefix: ${{ github.event.inputs.version-prefix }}
        version-suffix: alpha.${{ github.event.inputs.version-patch }}
        delay: 5m

  release-beta:
    if: github.ref == 'refs/heads/beta-release'
    environment: release-beta
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Push packaget to NuGet
      uses: ./actions/push
      with:
        version-prefix: ${{ env.version-prefix }}
        version-suffix: beta.${{ env.version-patch }}
        source: ${{ env.nuget-source }}
        source-api-key: ${{ secrets.NUGET_API_KEY }}
      
  release-beta-validation:
    needs: release-beta
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Test release
      uses: ./actions/test-release
      with:
        version-prefix: ${{ github.event.inputs.version-prefix }}
        version-suffix: beta.${{ github.event.inputs.version-patch }}
        delay: 5m

  release:
    if: github.ref == 'refs/heads/release'
    environment: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Push packaget to NuGet
      uses: ./actions/push
      with:
        version-prefix: ${{ env.version-prefix }}
        version-suffix: ''
        source: ${{ env.nuget-source }}
        source-api-key: ${{ secrets.NUGET_API_KEY }}
      
  release-validation:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Test release
      uses: ./actions/test-release
      with:
        version-prefix: ${{ github.event.inputs.version-prefix }}
        version-suffix: ''
        delay: 5m