name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
          
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies and build
        run: dotnet build --configuration Release /warnaserror
      - name: Test
        run: dotnet test --no-build --framework net5.0 --verbosity normal --configuration Release
