name: 'Test: Base'

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  solution: NClient.sln

jobs:
  build:
    name: Build with ${{ matrix.target-frameworks }}
    strategy:
      matrix:
        target-frameworks: [net48, net5.0, net6.0]
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build with ${{ matrix.target-frameworks }}
        uses: ./.github/actions/build
        with:
          target-framework: ${{ matrix.target-frameworks }}
          solution: Tests.slnf
          
  test-dotnet-framework:
    name: Test with ${{ matrix.target-frameworks }} on ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [windows-latest]
        target-frameworks: [net48]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Test with ${{ matrix.target-frameworks }}
        uses: ./.github/actions/test-framework
        with:
          target-framework: ${{ matrix.target-frameworks }}
          solution: ${{ env.solution }}
          
  test-dotnet-core:
    name: Test with ${{ matrix.target-frameworks }} on ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest]
        target-frameworks: [net5.0, net6.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Test with ${{ matrix.target-frameworks }}
        uses: ./.github/actions/test-core
        with:
          target-framework: ${{ matrix.target-frameworks }}
          solution: ${{ env.solution }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_token: ${{ secrets.GIST_TOKEN }}
      - name: Generate report for ${{ matrix.target-frameworks }}
        uses: zyborg/dotnet-tests-report@v1
        with:
          test_results_path: ${{ matrix.target-frameworks }}.trx
          no_build: true
          msbuild_verbosity: normal
          extra_test_parameters: '--framework ${{ matrix.target-frameworks }} --configuration Release'
          report_name: Test for ${{ matrix.target-frameworks }}
          report_title: Test for ${{ matrix.target-frameworks }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: test_for_${{ matrix.target-frameworks }}.md
          gist_badge_label: 'Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
          